import type { LearningEntry } from '@/types/entry'

const now = new Date().toISOString()

export const sampleEntries: LearningEntry[] = [
  {
    id: 'entry-particle-wa-ga',
    title: '终于分清了「は」与「が」在语气上的落点',
    date: '2026-06-09',
    insight: '以前只记“は提示主题、が提示主语”，但今天开始能从说话者真正想强调的部分去判断。',
    confusion: '一看到「が」就以为是在做语法填空题，听力里完全抓不住它为什么要出现。',
    resolution: '回放例句后，把句子拆成“信息背景”和“新信息”，再对比老师讲的语境差异，发现「が」常常是在把听者注意力拉到新出现的信息上。',
    finalGain: '我不再死记语法标签，而是开始从说话意图和信息焦点理解助词，这让我听句子时更自然。',
    tags: ['助词', '语感', '听力'],
    status: 'resolved',
    milestoneLevel: 'breakthrough',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'entry-shadowing-break',
    title: '第一次完整跟读完一分钟素材没有卡壳',
    date: '2026-06-05',
    insight: '跟读时只盯着音节不够，需要同时记住句群节奏和情绪重音。',
    confusion: '一到长句就会提前紧张，后半段经常还没听清就已经错过节奏。',
    resolution: '把原文按照呼吸点和语气切成三段，每段单独 shadowing，再连起来练，明显轻松很多。',
    finalGain: '我第一次感受到“不是我发不出来，而是我没有先听见节奏”，对口语训练有了真正的抓手。',
    tags: ['口语', '跟读', '节奏'],
    status: 'resolved',
    milestoneLevel: 'mastery',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'entry-te-form',
    title: 'て形变形还是会慢半拍',
    date: '2026-06-02',
    insight: '我已经能看懂大多数基础动词变化，但在输出时速度还不稳定。',
    confusion: '遇到五段动词时会下意识在脑内回忆规则表，导致说句子的时候不连贯。',
    resolution: '还在尝试把动词按音便分组背熟，并配合短句替换练习。',
    finalGain: '目前还没有彻底解决，但已经知道问题不在规则本身，而在自动化程度不够。',
    tags: ['动词变形', '语法', '输出'],
    status: 'ongoing',
    milestoneLevel: 'step',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'entry-kanji-radical',
    title: '开始用部首和语义网络记汉字，不再只靠硬背',
    date: '2026-05-28',
    insight: '把汉字拆成部件后，记忆路径从“像不像”变成了“为什么这么写”。',
    confusion: '同一批长得像的字总会串掉，比如「待」「持」「特」看久了都会混。',
    resolution: '我给每个部件单独写了含义提示，再配合例词和短语复现，记忆稳定度提升很多。',
    finalGain: '我第一次拥有了系统的识字方法，背单词时不再只是机械重复。',
    tags: ['汉字', '词汇', '记忆法'],
    status: 'resolved',
    milestoneLevel: 'spark',
    createdAt: now,
    updatedAt: now,
  },
]
